# Generated by Django 3.1.6 on 2021-02-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientDashboard', '0002_auto_20210226_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='carImg',
            field=models.ImageField(blank=True, upload_to='cars/'),
        ),
    ]
