# Generated by Django 3.1.6 on 2021-02-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientDashboard', '0003_auto_20210226_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='carImg',
            field=models.ImageField(blank=True, max_length=200, upload_to='cars/'),
        ),
    ]
