# Generated by Django 3.1.6 on 2021-02-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientDashboard', '0004_auto_20210226_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='fuelType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='transmission',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='carImg',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
