# Generated by Django 3.1.6 on 2021-03-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientDashboard', '0005_auto_20210226_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingaccount',
            name='transactionDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
