# Generated by Django 3.1.6 on 2021-03-27 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientDashboard', '0006_auto_20210325_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='driver_id',
        ),
    ]
