# Generated by Django 3.1.6 on 2021-03-27 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientDashboard', '0007_remove_bookingdetails_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='driver_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bddriverDetails', to='clientDashboard.driverdetails'),
            preserve_default=False,
        ),
    ]
